repos:
  - repo: local
    hooks:
      - id: alejandra
        name: alejandra
        entry: alejandra
        language: system
        types: [nix]
      - id: statix
        name: statix
        entry: statix check
        language: system
        types: [nix]
      - id: deadnix
        name: deadnix
        entry: deadnix --fail
        language: system
        types: [nix]
        pass_filenames: false
      - id: nix-flake-check
        name: nix flake check
        entry: nix flake check
        language: system
        pass_filenames: false

default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

default_stages:
  - commit
  - push

ci:
  autoupdate_schedule: quarterly
  skip: []
