repos:
  - repo: https://github.com/cachix/pre-commit-hooks.nix
    rev: 50b9238891e388c9fdc6a5c49e49c42533a1b5ce
    hooks:
      - id: alejandra
      - id: statix
      - id: deadnix
      - id: treefmt
        args: ["--fail-on-change"]
  - repo: local
    hooks:
      - id: nix-flake-check
        name: nix flake check
        entry: nix flake check
        language: system
        pass_filenames: false

default_install_hook_types:
  - pre-commit
  - commit-msg

ci:
  autoupdate_schedule: quarterly
  skip: []
