# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ghostty = {
    pname = "ghostty";
    version = "1c2db85aa41c7d929cb23b408229e297dce2758a";
    src = fetchFromGitHub {
      owner = "ghostty-org";
      repo = "ghostty";
      rev = "1c2db85aa41c7d929cb23b408229e297dce2758a";
      fetchSubmodules = false;
      sha256 = "sha256-yp3n4aKlG1lZDkQl3sDD7smjNjGFeEErVaiQlorzxrk=";
    };
    date = "2026-01-01";
  };
}
